server:
  port: 8070

# Configuration de la base de données H2
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # Configuration du dialecte de la base de données
  jpa:
    hibernate:
      ddl-auto: update  # Définit la stratégie de mise à jour de la base de données : 'none', 'update', 'create', 'create-drop'
      show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  # Console H2 activée pour visualiser la base de données dans un navigateur
  h2:
    console:
      enabled: true
      path: /h2-console



# identifiant de connexion
  security:
    user:
      name: igor
      password: password123
      roles: USER
